//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARventure_Path.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class arventure
    {
        public arventure()
        {
            this.happening = new HashSet<happening>();
            this.user = new HashSet<user>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int idRoute { get; set; }
        public int idStory { get; set; }
        public int idAchievement { get; set; }
    
        public virtual achievement achievement { get; set; }
        public virtual route route { get; set; }
        public virtual story story { get; set; }
        public virtual ICollection<happening> happening { get; set; }
        public virtual ICollection<user> user { get; set; }
    }
}
