//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARventure_Path.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class route
    {
        public route()
        {
            this.arventure = new HashSet<arventure>();
            this.stop = new HashSet<stop>();
        }
    
        public int id { get; set; }
        public System.TimeSpan time { get; set; }
        public Nullable<int> steps { get; set; }
        public double distance { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<arventure> arventure { get; set; }
        public virtual ICollection<stop> stop { get; set; }
    }
}
